apiVersion: v1
kind: Service
metadata:
  labels:
    app: myapp
  name: myapp-svc
  namespace: default
spec:
  ports:
  - nodePort: 30123
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: hpe
  type: NodePort
