apiVersion: v1
kind: ReplicationController
metadata:
  name: testapp
spec:
  replicas: 2
  selector:
    name: testapp
  template:
    metadata:
      labels:
        name: testapp
    spec:
      containers:
      - image: smlinux/appjs		
        name: appjs
        ports:
        - containerPort: 8080

