apiVersion: v1
kind: Pod
metadata:
  name: multi
spec:
  containers:
  - name: nginx-container
    image: nginx
    volumeMounts:
    - name: shared-data
      mountPath: /usr/share/nginx/html

  - name: ubuntu-container
    image: ubuntu
    volumeMounts:
    - name: shared-data
      mountPath: /web-data
    command: ["/bin/bash"]
    args: ["-c", "echo Hello HPE > /web-data/index.html"]

  volumes:
  - name: shared-data
    emptyDir: {}
