apiVersion: v1
kind: ReplicationController
metadata:
  name: testpod
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: hpe
    spec:
      containers:
      - image: smlinux/appjs
        name: testcon
        ports:
        - containerPort: 8080
