apiVersion: v1
kind: ReplicationController
metadata:
  name: app-v1
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: hpe
    spec:
      containers:
      - image: smlinux/app:v1
        name: app
        ports:
        - containerPort: 8080
