apiVersion: v1
kind: ReplicationController
metadata:
  name: nodeinfo
spec:
  replicas: 3
  selector:
     name: nodeinfo
  template:
    metadata:
      labels:
        name: nodeinfo
    spec:
      containers:
      - image: smlinux/node-info
        name: nodeinfo
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nodeinfo
spec:
  selector:
    name: nodeinfo
  ports:
  - port: 80
